# Generated by Django 5.2.17 on 2026-09-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='locale',
            field=models.CharField(choices=[('ne', 'ne'), ('ne-Latn', 'ne-Latn'), ('hi-Latn', 'hi-Latn'), ('en', 'en')], default='ne', max_length=16),
        ),
    ]
