# Generated by Django 5.2.17 on 2026-09-24 07:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_device_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, default='', max_length=128)),
                ('recovery_code_hash', models.CharField(blank=True, default='', max_length=64)),
                ('recovery_code_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounts_account',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='bound_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='label',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='device',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='accounts.account'),
        ),
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('email', 'Email'), ('username', 'Username'), ('google', 'Google')], max_length=16)),
                ('value_hash', models.CharField(db_index=True, max_length=64)),
                ('value_encrypted', models.TextField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='accounts.account')),
            ],
            options={
                'db_table': 'accounts_identifier',
                'constraints': [models.UniqueConstraint(fields=('kind', 'value_hash'), name='unique_identifier_per_kind')],
            },
        ),
    ]
